Arm 64 support
Coverd/phpqa pull request #6
Opened 2022-03-28 12:57 UTC by smnandre

(wip)

2022-03-28 13:02 UTC, odolbeau requested changes
Plein de double sauts de ligne inutiles. :p

2022-03-28 13:02 UTC, odolbeau commented on README.md
> +docker buildx rm --all-inactive --force
```
docker: 'buildx' is not a docker command.
```
:shrug:

2022-03-28 13:03 UTC, smnandre commented on README.md
> +docker buildx rm --all-inactive --force
Mais mais mais... c'est en DRAFT :p 

buildx c'est étonnant en revanche. T'es sous quelle version de Docker ?

2022-03-28 13:28 UTC, odolbeau commented on README.md
> +docker buildx rm --all-inactive --force
19.03.15, build 99e3ed8919

2022-03-28 15:52 UTC, smnandre commented on README.md
> +docker buildx rm --all-inactive --force
@odolbeau est-ce que tu peux regarder sur cette page si c'est pas juste un problème de path ?

--> https://docs.docker.com/buildx/working-with-buildx/

2022-03-30 08:10 UTC, odolbeau approved these changes

2022-03-30 08:11 UTC, merged